services:
  - type: web
    name: autoseed-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    rootDir: backend
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
